import { chromium } from "playwright";
import path from "node:path";
const pid = process.argv[2];
const ctx = await chromium.launchPersistentContext(path.resolve("secrets/octane-profile"), { headless: true, args: ["--disable-blink-features=AutomationControlled"] });
const page = await ctx.newPage();
await page.goto("https://octane.site/content", { waitUntil: "domcontentloaded", timeout: 45000 });
await page.waitForTimeout(2000);
const out = await page.evaluate(`(async () => {
  const pid = ${JSON.stringify(process.argv[2])};
  const html = await fetch("/page/" + pid).then(r => r.text());
  const grab = (n) => (html.match(new RegExp('name="' + n + '"[^>]*value="([^"]*)"')) || html.match(new RegExp('value="([^"]*)"[^>]*name="' + n + '"')) || [])[1] || "";
  const title = (html.match(/<title>([^<]*)</) || [])[1] || "";
  if (!/Full Width Content/.test(title)) return "SKIP not-a-section: " + title;
  const fd = new URLSearchParams();
  fd.set("_token", grab("_token"));
  fd.set("_method", "PUT");
  fd.set("siteid", grab("siteid") || "2418");
  fd.set("published", "no");
  fd.set("publishdate", "");
  fd.set("featured", grab("featured") || "0");
  fd.set("custom1", grab("custom1"));
  fd.set("whichupdate", "publish");
  const res = await fetch("/page/" + pid, { method: "POST", headers: { "X-Requested-With": "XMLHttpRequest" }, body: fd });
  return "unpublished -> " + res.status;
})()`);
console.log(pid, out);
await ctx.close();
